APP_NAME: "go_bank_app"
APP_PORT: "33001"

# MongoDB URI
#DB_URI: "mongodb://user:password@localhost:27017/dbname?authMechanism=SCRAM-SHA-1"
#DB_NAME: "dbname"

# Postgres
DB_URI: "postgresql://postgres:Sw@pnil3650!@localhost:5432/bank?sslmode=disable"
