export const CREATE_USER_INITIATE = "CREATE_USER_INITIATE";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const LOGIN_USER_INITIATE ="LOGIN_USER_INITIATE"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"
export const LOGOUT_USER = "LOGOUT_USER"
export const UPDATE_USER_INFO = "ADD_USER_INFO";
