export const CREATE_USER_INITIATE = "CREATE_USER_INITIATE";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const ADD_USER_INFO = "ADD_USER_INFO";
export const REMOVE_USER_INFO = "REMOVE_USER_INFO";